### ISSUE TITLE
Incorrect help message when arguments have underscores

### ISSUE THREAD

**Issue by mrzv** [piranha/opster#60]
Two almost identical functions (only difference is the underscore in the `arugment`) produce two different help messages
```
@command()
def show(name, place = '', argument = ('a', False, 'some argument')):
    print(name)
```
results in
```
problem.py show [OPTIONS] NAME [PLACE]

[...]

 -a --argument  some argument
```

```
@command()
def show(name, place = '', argu_ment = ('a', False, 'some argument')):
    print(name)
```
results in
```
problem.py show [OPTIONS] NAME [PLACE] [ARGU_MENT]

[...]

 -a --argu-ment  some argument
```

The ``[ARGU_MENT]`` doesn't belong in the latter command line.

**Comment by piranha** [comment]
Hah, that's weird. Not sure I'll look soon into the issue, but if you (or anybody else) is willing to make a pull request I'll gladly merge it. :)
